POST  http://localhost:4000/notification/test 
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
    "title":"Test Notification",
    "body":"This is a test notification",
    "data": {
        "type": "test"
    }
}